// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBsqNcTct5KHbOYpwEIhS62whGMbGgi8',
    appId: '1:374261583168:android:e181c523a4cd2cb5f4fea5',
    messagingSenderId: '374261583168',
    projectId: 'kapi-dominos',
    storageBucket: 'kapi-dominos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzvYkoAjPEd6gzpd7Pf5KNkGgSF_DcZfI',
    appId: '1:374261583168:ios:1d0797f1c43d33f3f4fea5',
    messagingSenderId: '374261583168',
    projectId: 'kapi-dominos',
    storageBucket: 'kapi-dominos.firebasestorage.app',
    iosBundleId: 'com.example.dominoesNote2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALJZPDeQJOUHLh9vV7QbxRp3qhKeV7vvQ',
    appId: '1:374261583168:web:498a23e76bb4fbcff4fea5',
    messagingSenderId: '374261583168',
    projectId: 'kapi-dominos',
    authDomain: 'kapi-dominos.firebaseapp.com',
    storageBucket: 'kapi-dominos.firebasestorage.app',
    measurementId: 'G-PDDGWDFQXC',
  );
}



